name: 3m4v
channels:
  - pytorch
  - defaults
dependencies:
  - scipy=1.6.0
  - pytorch=1.7.1
  - ipykernel
  - pandas
  - cudatoolkit=10.2.89
  - numpy=1.19.2
  - numba[version='>=0.49']
  - scikit-learn=0.23.2
  - matplotlib=3.3.2
  - python=3.8.5
  - pytorch=1.7.1
  - cython
  - seaborn
  - pynndescent
  - intel-openmp
  - torchvision
  - pip:
      - pykeops==1.5